import fs from "node:fs";
import path from "node:path";
import { DOCUMENT_ACTION_DESCRIPTORS } from "../src/core/actions/projections";

const outputPath = path.join(
  process.cwd(),
  "docs",
  "DOCUMENT-ACTIONS.generated.md",
);

function tableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

const rows = DOCUMENT_ACTION_DESCRIPTORS.map((action) =>
  [
    `\`${action.id}\``,
    `\`${action.category}\``,
    `\`${action.i18nKey}\``,
    `\`${tableCell(JSON.stringify(action.argsSchema))}\``,
  ].join(" | "),
);

const output = [
  "<!-- Generated by scripts/generate-document-actions.ts. Do not edit. -->",
  "",
  "# Document Actions",
  "",
  "Every action accepts one strict JSON object. The schemas below are projected",
  "from the runtime `DocumentActionDefinition.argsSchema` values used for",
  "validation and execution.",
  "",
  `Action count: ${DOCUMENT_ACTION_DESCRIPTORS.length}.`,
  "",
  "ID | Category | i18n key | Arguments JSON Schema",
  "--- | --- | --- | ---",
  ...rows,
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";
  if (current !== output) {
    process.stderr.write(
      "Generated action documentation is stale. Run `npm run docs:actions`.\n",
    );
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(outputPath, output);
}
